"""
Screenshot capture tests for the sixtop system monitor.

These tests render each metric view and save screenshots as PNG files,
which are uploaded as CI artifacts for visual inspection.

Screenshots are generated by:
1. Rendering each view to a pixel buffer
2. Converting the pixel buffer directly to PNG using PIL
"""

import platform
import pytest
from pathlib import Path
import sys

# Add the sixtop package to the path
sixtop_dir = Path(__file__).parent.parent
sys.path.insert(0, str(sixtop_dir))

from renderer import MetricsRenderer, MetricView, VIEW_TITLES
from sixel import pixels_to_png, create_pixel_buffer, COLOR_INDICES


# Output directory for screenshots
SCREENSHOT_DIR = Path(__file__).parent.parent / "screenshots"


def get_os_name() -> str:
    """Get a clean OS name for the screenshot filename."""
    system = platform.system().lower()
    if system == "darwin":
        return "macos"
    return system


@pytest.fixture(scope="module", autouse=True)
def setup_screenshot_dir():
    """Create the screenshots directory before tests run."""
    SCREENSHOT_DIR.mkdir(parents=True, exist_ok=True)
    yield


def save_renderer_screenshot(
    renderer: MetricsRenderer,
    mock_metrics,
    output_path: Path,
    stats_ready: bool = True
) -> bool:
    """
    Save a screenshot of the current renderer state as a PNG.

    Args:
        renderer: The MetricsRenderer to capture
        mock_metrics: Mock metrics data
        output_path: Path to save the PNG file
        stats_ready: Whether stats are ready (affects display)

    Returns:
        True if successful, False otherwise
    """
    # Create pixel buffer with background
    pixels = create_pixel_buffer(
        renderer.width,
        renderer.height,
        COLOR_INDICES["background"]
    )

    # Draw frame border
    renderer._draw_frame_border(pixels)

    # Draw instructions at top
    renderer._draw_instructions(pixels)

    # Render the appropriate view
    if renderer.current_view == MetricView.ENERGY:
        renderer._render_energy_view(pixels, mock_metrics, stats_ready)
    elif renderer.current_view == MetricView.CPU:
        renderer._render_cpu_view(pixels, mock_metrics, stats_ready)
    elif renderer.current_view == MetricView.IO:
        renderer._render_io_view(pixels, mock_metrics, stats_ready)
    elif renderer.current_view == MetricView.MEMORY:
        renderer._render_memory_view(pixels, mock_metrics, stats_ready)
    elif renderer.current_view == MetricView.NETWORK:
        renderer._render_network_view(pixels, mock_metrics, stats_ready)

    # Save as PNG
    result = pixels_to_png(pixels, str(output_path))
    return result is not None


class TestViewScreenshots:
    """Capture screenshots of each metric view."""

    def test_cpu_view(self, mock_metrics):
        """Capture a screenshot of the CPU view."""
        renderer = MetricsRenderer()
        renderer.current_view = MetricView.CPU

        os_name = get_os_name()
        output_path = SCREENSHOT_DIR / f"view_cpu_{os_name}.png"

        success = save_renderer_screenshot(renderer, mock_metrics, output_path)
        assert success, f"Failed to save screenshot: {output_path}"
        assert output_path.exists(), f"Screenshot not found at {output_path}"

        file_size = output_path.stat().st_size
        assert file_size > 0, "Screenshot file is empty"
        print(f"\nScreenshot saved: {output_path} ({file_size} bytes)")

    def test_memory_view(self, mock_metrics):
        """Capture a screenshot of the Memory view."""
        renderer = MetricsRenderer()
        renderer.current_view = MetricView.MEMORY

        os_name = get_os_name()
        output_path = SCREENSHOT_DIR / f"view_memory_{os_name}.png"

        success = save_renderer_screenshot(renderer, mock_metrics, output_path)
        assert success, f"Failed to save screenshot: {output_path}"
        assert output_path.exists(), f"Screenshot not found at {output_path}"

        file_size = output_path.stat().st_size
        print(f"\nScreenshot saved: {output_path} ({file_size} bytes)")

    def test_io_view(self, mock_metrics):
        """Capture a screenshot of the I/O view."""
        renderer = MetricsRenderer()
        renderer.current_view = MetricView.IO

        os_name = get_os_name()
        output_path = SCREENSHOT_DIR / f"view_io_{os_name}.png"

        success = save_renderer_screenshot(renderer, mock_metrics, output_path)
        assert success, f"Failed to save screenshot: {output_path}"
        assert output_path.exists(), f"Screenshot not found at {output_path}"

        file_size = output_path.stat().st_size
        print(f"\nScreenshot saved: {output_path} ({file_size} bytes)")

    def test_network_view(self, mock_metrics):
        """Capture a screenshot of the Network view."""
        renderer = MetricsRenderer()
        renderer.current_view = MetricView.NETWORK

        os_name = get_os_name()
        output_path = SCREENSHOT_DIR / f"view_network_{os_name}.png"

        success = save_renderer_screenshot(renderer, mock_metrics, output_path)
        assert success, f"Failed to save screenshot: {output_path}"
        assert output_path.exists(), f"Screenshot not found at {output_path}"

        file_size = output_path.stat().st_size
        print(f"\nScreenshot saved: {output_path} ({file_size} bytes)")

    def test_energy_view(self, mock_metrics):
        """Capture a screenshot of the Energy view."""
        renderer = MetricsRenderer()
        renderer.current_view = MetricView.ENERGY

        os_name = get_os_name()
        output_path = SCREENSHOT_DIR / f"view_energy_{os_name}.png"

        success = save_renderer_screenshot(renderer, mock_metrics, output_path)
        assert success, f"Failed to save screenshot: {output_path}"
        assert output_path.exists(), f"Screenshot not found at {output_path}"

        file_size = output_path.stat().st_size
        print(f"\nScreenshot saved: {output_path} ({file_size} bytes)")


class TestBatteryStateScreenshots:
    """Capture screenshots with different battery states."""

    def test_battery_high(self, mock_metrics):
        """Capture energy view with high battery (>50%)."""
        mock_metrics.battery.has_battery = True
        mock_metrics.battery.charge_percent = 85.0
        mock_metrics.battery.is_charging = False

        renderer = MetricsRenderer()
        renderer.current_view = MetricView.ENERGY

        os_name = get_os_name()
        output_path = SCREENSHOT_DIR / f"battery_high_{os_name}.png"

        success = save_renderer_screenshot(renderer, mock_metrics, output_path)
        assert success, f"Failed to save screenshot: {output_path}"

        file_size = output_path.stat().st_size
        print(f"\nScreenshot saved: {output_path} ({file_size} bytes)")

    def test_battery_medium(self, mock_metrics):
        """Capture energy view with medium battery (21-50%)."""
        mock_metrics.battery.has_battery = True
        mock_metrics.battery.charge_percent = 35.0
        mock_metrics.battery.is_charging = False

        renderer = MetricsRenderer()
        renderer.current_view = MetricView.ENERGY

        os_name = get_os_name()
        output_path = SCREENSHOT_DIR / f"battery_medium_{os_name}.png"

        success = save_renderer_screenshot(renderer, mock_metrics, output_path)
        assert success, f"Failed to save screenshot: {output_path}"

        file_size = output_path.stat().st_size
        print(f"\nScreenshot saved: {output_path} ({file_size} bytes)")

    def test_battery_low(self, mock_metrics):
        """Capture energy view with low battery (<=20%)."""
        mock_metrics.battery.has_battery = True
        mock_metrics.battery.charge_percent = 15.0
        mock_metrics.battery.is_charging = False

        renderer = MetricsRenderer()
        renderer.current_view = MetricView.ENERGY

        os_name = get_os_name()
        output_path = SCREENSHOT_DIR / f"battery_low_{os_name}.png"

        success = save_renderer_screenshot(renderer, mock_metrics, output_path)
        assert success, f"Failed to save screenshot: {output_path}"

        file_size = output_path.stat().st_size
        print(f"\nScreenshot saved: {output_path} ({file_size} bytes)")

    def test_no_battery(self, mock_metrics):
        """Capture energy view with no battery (desktop)."""
        mock_metrics.battery.has_battery = False

        renderer = MetricsRenderer()
        renderer.current_view = MetricView.ENERGY

        os_name = get_os_name()
        output_path = SCREENSHOT_DIR / f"no_battery_{os_name}.png"

        success = save_renderer_screenshot(renderer, mock_metrics, output_path)
        assert success, f"Failed to save screenshot: {output_path}"

        file_size = output_path.stat().st_size
        print(f"\nScreenshot saved: {output_path} ({file_size} bytes)")


class TestStatsNotReadyScreenshots:
    """Capture screenshots when stats are not yet ready."""

    def test_cpu_not_ready(self, mock_metrics):
        """Capture CPU view before stats are collected."""
        renderer = MetricsRenderer()
        renderer.current_view = MetricView.CPU

        os_name = get_os_name()
        output_path = SCREENSHOT_DIR / f"cpu_not_ready_{os_name}.png"

        success = save_renderer_screenshot(
            renderer, mock_metrics, output_path, stats_ready=False
        )
        assert success, f"Failed to save screenshot: {output_path}"

        file_size = output_path.stat().st_size
        print(f"\nScreenshot saved: {output_path} ({file_size} bytes)")


class TestAllViewsCycle:
    """Test cycling through all views generates valid screenshots."""

    def test_all_views_cycle(self, mock_metrics):
        """Cycle through all views and save a combined screenshot set."""
        renderer = MetricsRenderer()
        os_name = get_os_name()

        for view in MetricView:
            renderer.current_view = view
            view_name = view.name.lower()
            output_path = SCREENSHOT_DIR / f"cycle_{view_name}_{os_name}.png"

            success = save_renderer_screenshot(renderer, mock_metrics, output_path)
            assert success, f"Failed to save {view.name} screenshot"

            file_size = output_path.stat().st_size
            assert file_size > 0, f"{view.name} screenshot is empty"
            print(f"  {view.name}: {output_path} ({file_size} bytes)")
